from models import VGG_FER_MODEL, UNET_MODEL
from datasets import FER_DATASET, FERPLUS_DATASET
from datasets import FER_METRICS, FERPLUS_METRICS


LEARNING_MACHINE_MODEL = VGG_FER_MODEL
PRETRAINED = False
DATASET_NAME = FERPLUS_DATASET
METRIC_DATASET_NAME = FERPLUS_METRICS
